-- MySQL Script generated by MySQL Workbench
-- Wed Sep 18 12:15:35 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Familia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Familia` (
  `idFamilia` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(80) NOT NULL,
  `limite` INT NULL,
  `codigo` VARCHAR(12) NOT NULL,
  PRIMARY KEY (`idFamilia`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Usuario` (
  `idUsuario` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(80) NULL,
  `data_nascimento` DATE NULL,
  `email` VARCHAR(50) NULL,
  `telefone` VARCHAR(11) NULL,
  `senha` VARCHAR(16) NULL,
  `parentesco` VARCHAR(20) NULL,
  `tipo` ENUM('administrador', 'integrante') NULL,
  `imagem` VARCHAR(255) NULL,
  `Familia_idFamilia` INT NOT NULL,
  PRIMARY KEY (`idUsuario`),
  INDEX `fk_Usuario_Familia_idx` (`Familia_idFamilia` ASC) ,
  CONSTRAINT `fk_Usuario_Familia`
    FOREIGN KEY (`Familia_idFamilia`)
    REFERENCES `mydb`.`Familia` (`idFamilia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Tarefa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Tarefa` (
  `idTarefa` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(80) NOT NULL,
  `data_inicio` DATE NOT NULL,
  `data_final` DATE NOT NULL,
  `prazo` DATE NULL,
  `pontuacao` INT NULL,
  `descricao` TEXT NULL,
  `status` ENUM('pendente', ' concluido', 'em_andamento') NOT NULL,
  `Usuario_idUsuario` INT NOT NULL,
  PRIMARY KEY (`idTarefa`),
  INDEX `fk_Tarefa_Usuario1_idx` (`Usuario_idUsuario` ASC),
  CONSTRAINT `fk_Tarefa_Usuario1`
    FOREIGN KEY (`Usuario_idUsuario`)
    REFERENCES `mydb`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


INSERT INTO `mydb`.`Familia`(`idFamilia`,`nome`,`limite`,`codigo`) VALUES ('SIlvanois',7,'adbr721'),('Jorgens',3,'12dc10r'),('Maia',4,'17toria'),('Souza',5,'58ol7g5'),('Lima',6,'6kj74');
;


 
INSERT INTO `mydb`.`Usuario`(`idUsuario`,`nome`,`data_nascimento`,`email`,`telefone`,`senha`,`parentesco`,`tipo`,`imagem`,`Familia_idFamilia`) VALUES (null,'Ana','27/8/1980','aninha_querida@gmail.com','11956782461','add3459','mãe','administrador','agrTDFVDVSD','adbr721'),
(null,'Rogerio','01/09/1978','roger_mau@hotmail.com','11936752171','au555','pai','administrador','rgwafsawadsdfgj','abd721'),
(null,'Claudia','07/12/2000','cl.audinha@gmail.com','11949728346','120945','filha','integrante','dgdhnfdhfgh','adbr721'),
(null,'Gilberta','15/3/1994','gilgil.gata@hotmail.com','11934528606','365472','tia','integrante','dfgtgfd','adbr721'),
(null,'Fernando','03/04/1950','fer_das_antigas@gmail.com','11946280557','13579','avô','integrante','ashbdhabhd','adbr721'),
 (null,'Claudio','07/12/2000','cl.audio@gmail.com','11987687214','12345','filho','integrante','sdiasuysid','adbr721'),


(null,'Gabriela','18/09/2002','Gabriela@hotmail.com','11912345678','125465487','filha','integrante','agrTDFVDVSD','12dc10r'),
(null,'Rogerio','01/09/1978','roger_mau@hotmail.com','11936752171','au555','pai','integrante','rgwafsawadsdfgj','12dc10r'),
(null,'Claudia','07/12/2000','cl.audinha@gmail.com','11949728346','120945','filha','integrante','dgdhnfdhfgh','12dc10r'),

(null,'Gabriela','18/89/1985','Gabriela@hotmail.com','11912345678','dmfdnsj','mãe','integrante','TDFVDVSD','17toria'),
(null,'Gabriel','11/05/1990','Gabriel@hotmail.com','11915323578','1253','filho','integrante','VDVSD','17toria'),
(null,'Gael','20/03/2003','Gael@hotmail.com','11912562658','125njsbdsd','filha','integrante','VSD125','17toria'),
(null,'Gustavo','08/09/1980','Gustavo@hotmail.com','11984625978','ju20387','pai','administrador','45786VSD','17toria'),

(null,'Adrian','07/02/1982','Adrian@hotmail.com','1195131545','12546j5487','pai','administrador','sdgfydDVSD','58ol7g5'),
(null,'Alan','05/03/2000','Alan@hotmail.com','11912125455','125465i2','filho','integrante','TDFVDVSD','58ol7g5'),
(null,'Ana','31/05/1998','Ana@hotmail.com','11915347541','1bcd487','filha','integrante','VDVSD','58ol7g5'),
(null,'Alana','28/07/1980','Alana@hotmail.com','119547412658','1cgt5487','mãe','integrante','VSD125','58ol7g5'),
(null,'Ariel','18/09/2002','Arielo@hotmail.com','11982455978','65487','filha','integrante','45786VSD','58ol7g5'),

(null,'Luiz','07/02/1970','Luiz@hotmail.com','1195131545','4445487','pai','integrante','sdgfydDVSD','6kj74'),
(null,'Luan','04/03/2000','Luan@hotmail.com','1198564758','125ftr2','filho','integrante','TDFVDVSD','6kj74'),
(null,'Lucas','01/05/1998','Lucas@hotmail.com','1198569745','1bcfdew','filho','integrante','VDVSD','6kj74'),
(null,'Leandro','02/07/2002','Leandro@hotmail.com','11953535879','724355','filho','integrante','VSD125','6kj74'),
(null,'Vitória','17/02/1971','Vitóriao@hotmail.com','1195820147','vivi17','mãe','administrador','45786VSD','6kj74'),
(null,'Luana','02/10/2005','Leandro@hotmail.com','119856879','Luluzita487','filha','integrante','VSD125','6kj74');


INSERT INTO `mydb`.`Tarefa`(`idTarefa`,`nome`,`data_inicio`,`data_final`,`prazo` ,`pontuacao`,`descricao`,`status`,`Usuario_idUsuario`) VALUES (null, 'passar pano', '14/04/2019', '15/04/2019', '1 dia', '3 pontos', 'feito', 'em andamento', 'idAdrian'),
(null, 'Adrian', '14/04/2019', '15/04/2019', '1 dia', null , 'passar pano', 'em andamento', '15Adrian'),
(null, 'Alan', '18/03/2019', '18/03/2019', '1 dia', '1 ponto', 'Molhar as plantas', 'em andamento', '11Alan'),
(null, 'Ana', '06/03/2019', '10/03/2019', '4 dias', '10 pontos', 'Lavar a casa', 'em andamento', '10Ana'),
(null, 'Alana', '03/03/2019', '05/03/2019', '2 dias', null, 'Lavar roupa', 'em andamento', '3Alana'),
(null, 'Ariel', '02/03/2019', '02/03/2019', ' alumas horas', '1 ponto', 'Lavar a louça', 'em andamento', '8Ariel'),

(null, 'Luiz', '06/03/2019', '10/03/2019', '4 dias', '10 pontos', 'Tirar pó da casa', 'em andamento', '12Luiz'),
(null, 'Luan', '05/03/2019', '08/03/2019', '3 dias', '10 pontos', 'estender a roupa', 'em andamento', '13Luan'),
(null, 'Lucas', '04/03/2019', '08/03/2019', '4 dias', '10 pontos', 'lavar o salão', 'em andamento', '11Lucas'),
(null, 'Leandro', '03/03/2019', '03/03/2019', '1 dias', '10 pontos', 'arrumar quarto', 'em andamento', '10Leandro'),
(null, 'Vitória', '02/03/2019', '10/03/2019', '6 dias', '20 pontos', 'Lavar a casa', 'em andamento', '9Vitória'),
(null, 'Luana', '01/03/2019', '05/03/2019', '4 dias', '10 pontos', 'arrumar guarda-roupas', 'em andamento', '1Luana'),

 (null,'dar banho no cachorro','17/02/2020','18/02/2020','1 dia',3,'comprar o shampoo e o  condicionador','pendente',1),
 (null,'lavar louça','24/09/2019','25/09/2019',null,'limpar o chão','pendente',2),
 (null,'limpar o quarto','10/07/2020','14/07/2020','4 dia',1,null,'Em_andamento',3),
 (null,'Gilberta','17/02/2020','19/02/2020','2 dia','1 ponto',null,'pendente',4),
 (null,'Arrumar o quarto' ,'Levar o cachorrro para pet shop','12/03/23','14/03/23','14/03/23', 10 ),
 (null,'cozinha o jantar','ajudar na lição de casa','limpar o telhado''12/03/23','13/03/23','13/03/23', 10);




SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;



